# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElectriDash' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElectriDash
  pod 'Alamofire', '~> 4.7'
  pod 'KeychainAccess'
  pod 'JWTDecode', '~> 2.1'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ScrollableGraphView'
  pod 'M13Checkbox'

  target 'ElectriDashTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
